import type { DiveSite } from '@/lib/types';

// Cozumel dive site seed — 30 sites curated from a research pass across
// Wannadive.net, PADI, Reef Smart Guides, Reefs of Cozumel, Blue Note Scuba,
// and ScubaBoard. Coordinates are best-available public waypoints; a few are
// marked "estimate" where no source publishes an exact coordinate.
//
// `id` uses the slug as a stable string for local development. When we push
// this seed into Supabase, gen_random_uuid() will assign real UUIDs and this
// file becomes read-through-cache / offline fallback.

const SEED_CREATED_AT = '2026-07-01T00:00:00.000Z';

export const cozumelSeed: DiveSite[] = [
  {
    id: 'san-juan',
    slug: 'san-juan',
    name: 'San Juan Reef',
    lat: 20.549,
    lng: -86.9318,
    description:
      "Deep sandy drift on the north end of the island with strong, sometimes downward currents and big-fish potential.",
    difficulty: 'advanced',
    max_depth_m: 35,
    site_type: 'drift',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'barracuda-reef',
    slug: 'barracuda-reef',
    name: 'Barracuda Reef',
    lat: 20.5427,
    lng: -86.9372,
    description:
      'A deep, exposed drift on the far north coast famed for barracuda, sharks, and eagle rays; Harbor Master authorization required.',
    difficulty: 'advanced',
    max_depth_m: 35,
    site_type: 'drift',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'villa-blanca-wall',
    slug: 'villa-blanca-wall',
    name: 'Villa Blanca Wall',
    lat: 20.5161,
    lng: -86.9543,
    description:
      'The closest wall south of San Miguel, dropping from a shallow reef shelf at ~15 m into deep blue water, often used as a drift into Cantarel.',
    difficulty: 'intermediate',
    max_depth_m: 33,
    site_type: 'wall',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'cozumel-plane-wreck',
    slug: 'cozumel-plane-wreck',
    name: 'Cozumel Plane Wreck',
    lat: 20.48,
    lng: -86.9737,
    description:
      'A shallow twin-engine plane wreck (movie prop) in front of the El Cid / former La Ceiba hotel, easily reached from shore or by short boat ride.',
    difficulty: 'beginner',
    max_depth_m: 15,
    site_type: 'wreck',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'paradise-reef',
    slug: 'paradise-reef',
    name: 'Paradise Reef',
    lat: 20.4686,
    lng: -86.9837,
    description:
      'Shallow, easy patch-reef system south of the cruise piers popular for check-out dives, night dives, and beginners.',
    difficulty: 'beginner',
    max_depth_m: 15,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'las-palmas-shallows',
    slug: 'las-palmas-shallows',
    name: 'Las Palmas Shallows',
    lat: 20.458,
    lng: -86.9905,
    description:
      'Sandy-bottomed reef opposite the Fiesta Americana hotel with schooling fish that slopes gently to a wall.',
    difficulty: 'beginner',
    max_depth_m: 30,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'c53-felipe-xicotencatl',
    slug: 'c53-felipe-xicotencatl',
    name: 'C-53 Felipe Xicoténcatl Wreck',
    lat: 20.4425,
    lng: -87.0003,
    description:
      'A 56 m Mexican Navy minesweeper sunk as an artificial reef in 2000 off Chankanaab, with penetration opportunities from ~10 to 24 m.',
    difficulty: 'intermediate',
    max_depth_m: 24,
    site_type: 'wreck',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'tormentos',
    slug: 'tormentos',
    name: 'Tormentos Reef',
    lat: 20.4408,
    lng: -87.0047,
    description:
      'A shallow drift over a series of patch reefs south of Chankanaab, famous for dense hard and soft corals and swim-through tunnels.',
    difficulty: 'intermediate',
    max_depth_m: 20,
    site_type: 'drift',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'chankanaab-bolones',
    slug: 'chankanaab-bolones',
    name: 'Chankanaab Bolones',
    lat: 20.4363,
    lng: -87.0115,
    description:
      'Big scattered coral heads (bolones) off Chankanaab Park with abundant marine life, ideal for training and photography.',
    difficulty: 'beginner',
    max_depth_m: 24,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'playa-corona',
    slug: 'playa-corona',
    name: 'Playa Corona',
    lat: 20.4354,
    lng: -87.0029,
    description:
      'Easy shore-entry reef at Km 8.5 of the Costera Sur, popular for first dives, snorkeling, and night dives.',
    difficulty: 'beginner',
    max_depth_m: 18,
    site_type: 'shore',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'yucab',
    slug: 'yucab',
    name: 'Yucab Reef',
    lat: 20.4055,
    lng: -87.0212,
    description:
      'Classic Cozumel drift over low coral heads on sand, often chosen as the second dive of the day for its moderate current and marine life.',
    difficulty: 'beginner',
    max_depth_m: 19,
    site_type: 'drift',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'punta-tunich',
    slug: 'punta-tunich',
    name: 'Punta Tunich',
    lat: 20.3928,
    lng: -87.0255,
    description:
      'Fast drift over a sloping reef and sand channel that can rip north toward San Francisco Wall, known for eagle rays in winter.',
    difficulty: 'intermediate',
    max_depth_m: 40,
    site_type: 'drift',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'cardona-reef',
    slug: 'cardona-reef',
    name: 'Cardona Reef',
    lat: 20.3844,
    lng: -87.0242,
    description:
      'A shallow patch reef used for training and easy second dives with good macro life and mild current.',
    difficulty: 'beginner',
    max_depth_m: 15,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'san-clemente',
    slug: 'san-clemente',
    name: 'San Clemente Reef',
    lat: 20.3817,
    lng: -87.0263,
    description:
      'A shallow, colorful reef between San Francisco Wall and Punta Tunich with clear water and low current.',
    difficulty: 'beginner',
    max_depth_m: 25,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'san-francisco-reef',
    slug: 'san-francisco-reef',
    name: 'San Francisco Reef / Wall',
    lat: 20.3707,
    lng: -87.0268,
    description:
      'A steep wall dive off Playa San Francisco with dramatic drop-offs and healthy sponges, often paired with Santa Rosa.',
    difficulty: 'intermediate',
    max_depth_m: 50,
    site_type: 'wall',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'santa-rosa-wall',
    slug: 'santa-rosa-wall',
    name: 'Santa Rosa Wall',
    lat: 20.3655,
    lng: -87.0274,
    description:
      "One of the Caribbean's premier wall dives with overhangs, swim-throughs, big sponges, and pelagic encounters in strong drift.",
    difficulty: 'intermediate',
    max_depth_m: 40,
    site_type: 'wall',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'paso-del-cedral',
    slug: 'paso-del-cedral',
    name: 'Paso del Cedral',
    lat: 20.3543,
    lng: -87.0283,
    description:
      "Coral-covered ridges nicknamed the 'turtle garden' for its resident greens and loggerheads, plus schooling grunts and snapper.",
    difficulty: 'intermediate',
    max_depth_m: 25,
    site_type: 'drift',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'cedral-wall',
    slug: 'cedral-wall',
    name: 'Cedral Wall',
    lat: 20.354,
    lng: -87.03,
    description:
      'The vertical drop-off just west of Cedral Pass, with big sponges, moray eels, and frequent turtle and eagle-ray sightings.',
    difficulty: 'intermediate',
    max_depth_m: 27,
    site_type: 'wall',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'la-francesa',
    slug: 'la-francesa',
    name: 'La Francesa Reef',
    lat: 20.3504,
    lng: -87.0277,
    description:
      'A relaxed drift over low coral formations inside the Cozumel Reefs National Park, commonly used as the second dive after Palancar.',
    difficulty: 'beginner',
    max_depth_m: 20,
    site_type: 'drift',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'dalila',
    slug: 'dalila',
    name: 'Punta Dalila',
    lat: 20.3454,
    lng: -87.0229,
    description:
      'Shallow bright coral heads on white sand with gentle currents, a reliable spot for nurse sharks and turtles.',
    difficulty: 'beginner',
    max_depth_m: 20,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'palancar-gardens',
    slug: 'palancar-gardens',
    name: 'Palancar Gardens',
    lat: 20.3361,
    lng: -87.0274,
    description:
      'The northernmost Palancar section, a garden of coral chutes, mini-walls, and swim-throughs with an arch at ~21 m.',
    difficulty: 'beginner',
    max_depth_m: 25,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'palancar-deep',
    slug: 'palancar-deep',
    name: 'Palancar Deep',
    lat: 20.3339,
    lng: -87.0306,
    description:
      "The outer Palancar wall of huge coral columns cited by Cousteau as one of the world's best dives; recreational limit reached quickly.",
    difficulty: 'advanced',
    max_depth_m: 40,
    site_type: 'wall',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'palancar-caves',
    slug: 'palancar-caves',
    name: 'Palancar Caves',
    lat: 20.3269,
    lng: -87.0302,
    description:
      'A labyrinth of caverns, tunnels, and swim-throughs threading through giant coral heads along the Palancar drop-off.',
    difficulty: 'intermediate',
    max_depth_m: 28,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'palancar-horseshoe',
    slug: 'palancar-horseshoe',
    name: 'Palancar Horseshoe',
    lat: 20.3266,
    lng: -87.0327,
    description:
      'A horseshoe-shaped cluster of massive coral pinnacles and buttresses regarded as one of the most photogenic dives on Palancar.',
    difficulty: 'intermediate',
    max_depth_m: 27,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'palancar-bricks',
    slug: 'palancar-bricks',
    name: 'Palancar Bricks',
    lat: 20.3204,
    lng: -87.0275,
    description:
      'Named for a stack of bricks from a shipwreck lying on the sand between coral formations along the southern Palancar section.',
    difficulty: 'intermediate',
    max_depth_m: 25,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'colombia-shallows',
    slug: 'colombia-shallows',
    name: 'Colombia Shallows',
    lat: 20.3164,
    lng: -87.0169,
    description:
      'A shallow coral-and-sand garden ideal for long, easy dives with schooling fish and turtles; the shallow companion to Colombia Deep.',
    difficulty: 'beginner',
    max_depth_m: 18,
    site_type: 'reef',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'colombia-deep',
    slug: 'colombia-deep',
    name: 'Colombia Deep',
    lat: 20.3122,
    lng: -87.0253,
    description:
      'Massive coral pinnacles and swim-throughs on the deep outer wall of Colombia Reef, a classic drift with pelagic encounters.',
    difficulty: 'advanced',
    max_depth_m: 40,
    site_type: 'wall',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'punta-sur-devils-throat',
    slug: 'punta-sur-devils-throat',
    name: "Punta Sur (Devil's Throat / Cathedral)",
    lat: 20.306,
    lng: -87.0257,
    description:
      "The legendary cavern system with the Devil's Throat chimney descending from ~27 m and exiting at ~40 m onto a sheer wall.",
    difficulty: 'advanced',
    max_depth_m: 40,
    site_type: 'wall',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'chun-chacaab',
    slug: 'chun-chacaab',
    name: 'Chun Chacaab',
    lat: 20.286,
    lng: -87.01,
    description:
      "Isolated coral 'reeflets' on sand between Punta Sur and Maracaibo with big gorgonians, eagle rays, and unpredictable current.",
    difficulty: 'advanced',
    max_depth_m: 27,
    site_type: 'drift',
    created_at: SEED_CREATED_AT,
  },
  {
    id: 'maracaibo',
    slug: 'maracaibo',
    name: 'Maracaibo Reef',
    lat: 20.278,
    lng: -87.005,
    description:
      'The southernmost site on the leeward reef, a deep wall with a huge coral arch reserved for experienced divers due to strong, unpredictable currents.',
    difficulty: 'advanced',
    max_depth_m: 45,
    site_type: 'wall',
    created_at: SEED_CREATED_AT,
  },
];
