-- Seed initial 30 Cozumel dive sites.
-- Idempotent: re-running via `supabase db push` upserts on slug.
-- Source of truth: src/lib/sites/seed-cozumel.ts

insert into public.dive_sites (slug, name, lat, lng, description, difficulty, max_depth_m, site_type)
values
  ('san-juan', 'San Juan Reef', 20.549, -86.9318,
   'Deep sandy drift on the north end of the island with strong, sometimes downward currents and big-fish potential.',
   'advanced', 35, 'drift'),
  ('barracuda-reef', 'Barracuda Reef', 20.5427, -86.9372,
   'A deep, exposed drift on the far north coast famed for barracuda, sharks, and eagle rays; Harbor Master authorization required.',
   'advanced', 35, 'drift'),
  ('villa-blanca-wall', 'Villa Blanca Wall', 20.5161, -86.9543,
   'The closest wall south of San Miguel, dropping from a shallow reef shelf at ~15 m into deep blue water, often used as a drift into Cantarel.',
   'intermediate', 33, 'wall'),
  ('cozumel-plane-wreck', 'Cozumel Plane Wreck', 20.48, -86.9737,
   'A shallow twin-engine plane wreck (movie prop) in front of the El Cid / former La Ceiba hotel, easily reached from shore or by short boat ride.',
   'beginner', 15, 'wreck'),
  ('paradise-reef', 'Paradise Reef', 20.4686, -86.9837,
   'Shallow, easy patch-reef system south of the cruise piers popular for check-out dives, night dives, and beginners.',
   'beginner', 15, 'reef'),
  ('las-palmas-shallows', 'Las Palmas Shallows', 20.458, -86.9905,
   'Sandy-bottomed reef opposite the Fiesta Americana hotel with schooling fish that slopes gently to a wall.',
   'beginner', 30, 'reef'),
  ('c53-felipe-xicotencatl', 'C-53 Felipe Xicoténcatl Wreck', 20.4425, -87.0003,
   'A 56 m Mexican Navy minesweeper sunk as an artificial reef in 2000 off Chankanaab, with penetration opportunities from ~10 to 24 m.',
   'intermediate', 24, 'wreck'),
  ('tormentos', 'Tormentos Reef', 20.4408, -87.0047,
   'A shallow drift over a series of patch reefs south of Chankanaab, famous for dense hard and soft corals and swim-through tunnels.',
   'intermediate', 20, 'drift'),
  ('chankanaab-bolones', 'Chankanaab Bolones', 20.4363, -87.0115,
   'Big scattered coral heads (bolones) off Chankanaab Park with abundant marine life, ideal for training and photography.',
   'beginner', 24, 'reef'),
  ('playa-corona', 'Playa Corona', 20.4354, -87.0029,
   'Easy shore-entry reef at Km 8.5 of the Costera Sur, popular for first dives, snorkeling, and night dives.',
   'beginner', 18, 'shore'),
  ('yucab', 'Yucab Reef', 20.4055, -87.0212,
   'Classic Cozumel drift over low coral heads on sand, often chosen as the second dive of the day for its moderate current and marine life.',
   'beginner', 19, 'drift'),
  ('punta-tunich', 'Punta Tunich', 20.3928, -87.0255,
   'Fast drift over a sloping reef and sand channel that can rip north toward San Francisco Wall, known for eagle rays in winter.',
   'intermediate', 40, 'drift'),
  ('cardona-reef', 'Cardona Reef', 20.3844, -87.0242,
   'A shallow patch reef used for training and easy second dives with good macro life and mild current.',
   'beginner', 15, 'reef'),
  ('san-clemente', 'San Clemente Reef', 20.3817, -87.0263,
   'A shallow, colorful reef between San Francisco Wall and Punta Tunich with clear water and low current.',
   'beginner', 25, 'reef'),
  ('san-francisco-reef', 'San Francisco Reef / Wall', 20.3707, -87.0268,
   'A steep wall dive off Playa San Francisco with dramatic drop-offs and healthy sponges, often paired with Santa Rosa.',
   'intermediate', 50, 'wall'),
  ('santa-rosa-wall', 'Santa Rosa Wall', 20.3655, -87.0274,
   'One of the Caribbean''s premier wall dives with overhangs, swim-throughs, big sponges, and pelagic encounters in strong drift.',
   'intermediate', 40, 'wall'),
  ('paso-del-cedral', 'Paso del Cedral', 20.3543, -87.0283,
   'Coral-covered ridges nicknamed the ''turtle garden'' for its resident greens and loggerheads, plus schooling grunts and snapper.',
   'intermediate', 25, 'drift'),
  ('cedral-wall', 'Cedral Wall', 20.354, -87.03,
   'The vertical drop-off just west of Cedral Pass, with big sponges, moray eels, and frequent turtle and eagle-ray sightings.',
   'intermediate', 27, 'wall'),
  ('la-francesa', 'La Francesa Reef', 20.3504, -87.0277,
   'A relaxed drift over low coral formations inside the Cozumel Reefs National Park, commonly used as the second dive after Palancar.',
   'beginner', 20, 'drift'),
  ('dalila', 'Punta Dalila', 20.3454, -87.0229,
   'Shallow bright coral heads on white sand with gentle currents, a reliable spot for nurse sharks and turtles.',
   'beginner', 20, 'reef'),
  ('palancar-gardens', 'Palancar Gardens', 20.3361, -87.0274,
   'The northernmost Palancar section, a garden of coral chutes, mini-walls, and swim-throughs with an arch at ~21 m.',
   'beginner', 25, 'reef'),
  ('palancar-deep', 'Palancar Deep', 20.3339, -87.0306,
   'The outer Palancar wall of huge coral columns cited by Cousteau as one of the world''s best dives; recreational limit reached quickly.',
   'advanced', 40, 'wall'),
  ('palancar-caves', 'Palancar Caves', 20.3269, -87.0302,
   'A labyrinth of caverns, tunnels, and swim-throughs threading through giant coral heads along the Palancar drop-off.',
   'intermediate', 28, 'reef'),
  ('palancar-horseshoe', 'Palancar Horseshoe', 20.3266, -87.0327,
   'A horseshoe-shaped cluster of massive coral pinnacles and buttresses regarded as one of the most photogenic dives on Palancar.',
   'intermediate', 27, 'reef'),
  ('palancar-bricks', 'Palancar Bricks', 20.3204, -87.0275,
   'Named for a stack of bricks from a shipwreck lying on the sand between coral formations along the southern Palancar section.',
   'intermediate', 25, 'reef'),
  ('colombia-shallows', 'Colombia Shallows', 20.3164, -87.0169,
   'A shallow coral-and-sand garden ideal for long, easy dives with schooling fish and turtles; the shallow companion to Colombia Deep.',
   'beginner', 18, 'reef'),
  ('colombia-deep', 'Colombia Deep', 20.3122, -87.0253,
   'Massive coral pinnacles and swim-throughs on the deep outer wall of Colombia Reef, a classic drift with pelagic encounters.',
   'advanced', 40, 'wall'),
  ('punta-sur-devils-throat', 'Punta Sur (Devil''s Throat / Cathedral)', 20.306, -87.0257,
   'The legendary cavern system with the Devil''s Throat chimney descending from ~27 m and exiting at ~40 m onto a sheer wall.',
   'advanced', 40, 'wall'),
  ('chun-chacaab', 'Chun Chacaab', 20.286, -87.01,
   'Isolated coral ''reeflets'' on sand between Punta Sur and Maracaibo with big gorgonians, eagle rays, and unpredictable current.',
   'advanced', 27, 'drift'),
  ('maracaibo', 'Maracaibo Reef', 20.278, -87.005,
   'The southernmost site on the leeward reef, a deep wall with a huge coral arch reserved for experienced divers due to strong, unpredictable currents.',
   'advanced', 45, 'wall')
on conflict (slug) do update set
  name = excluded.name,
  lat = excluded.lat,
  lng = excluded.lng,
  description = excluded.description,
  difficulty = excluded.difficulty,
  max_depth_m = excluded.max_depth_m,
  site_type = excluded.site_type;
