-- Seed Cozumel species catalog.
-- Common+scientific names cross-referenced from Caribbean Reef Life (Charteris 3rd ed).
-- Descriptions are intentionally null; app authors originate copy per licensing decision.

insert into public.species (slug, common_name, scientific_name, category, source_reference, is_verified)
values
('green-helmet-grape-alga', 'Green Helmet Grape Alga', 'Caulerpa lamourouxii', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('asparagus-alga', 'Asparagus Alga', 'Asparagopsis taxiformis', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('balled-blade-alga', 'Balled Blade Alga', 'Penicillus capitatus', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('manatee-grass', 'Manatee Grass', 'Halophila baillonis', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cemented', 'Cemented', 'Avrainvillea asarifolia', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('green-feather-alga', 'Green Feather Alga', 'Caulerpa cupressoides', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blistered-saucer-leaf-alga', 'Blistered Saucer Leaf Alga', 'Hincksia onslowensis', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('green-net-alga', 'Green Net Alga', 'Anadyomene stellata', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('small-leaf-hanging-vine', 'Small Leaf Hanging Vine', 'Halimeda copiosa', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('branching-bulb-alga', 'Branching Bulb Alga', 'Aglaothamnion herveyi', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('branching-leaf-alga', 'Branching Leaf Alga', 'Acetabularia incrassata', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bristle-ball-brush', 'Bristle Ball Brush', 'Amphiroa opuntia', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('leafy-flat-blade-alga', 'Leafy Flat Blade Alga', 'Padina boergesenii', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-mangrove', 'Black Mangrove', 'Avicennia germinans', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('creeping-branch-alga', 'Creeping Branch Alga', 'Neomeris annulata', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('creeping-bubble-alga', 'Creeping Bubble Alga', 'Valonia macrophysa', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('burgundy-crust-alga', 'Burgundy Crust Alga', 'Lithothamnion ruptile', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('lavender', 'Lavender', 'Hydrolithon farinosum', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('green-mermaid-s-wineglass', 'Green Mermaid’s Wineglass', 'Acetabularia caliculus', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('rose-red', 'Rose-Red', 'Dictyopteris inamoena', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('mucosa-pink-alga', 'Mucosa Pink Alga', 'Ganonema farinosum', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cryptic-blade-alga', 'Cryptic Blade Alga', 'Martensia pavonia', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cyanobacteria', 'Cyanobacteria', 'Cladosiphon plumata', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('fuzz-ball-alga', 'Fuzz Ball Alga', 'Caldora penicillata', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('narrow-blade-alga', 'Narrow Blade Alga', 'Lobophora variegata', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('oscillatoria', 'Oscillatoria', 'Red Band', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('rubbery-bush-alga', 'Rubbery Bush Alga', 'Halymenia duchassaingii', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('fuzzy-caulerpa', 'Fuzzy Caulerpa', 'Microdictyon verticillata', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('flat-blade-sargassum', 'Flat-Blade Sargassum', 'Sargassum acinarium', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('variable-boring-sponge', 'Variable Boring Sponge', 'Siphonodictyon coralliphagum', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brain-sponge', 'Brain Sponge', 'Agelas cerebrum', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('branchlet-sponge', 'Branchlet Sponge', 'Aplysina archeri', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brown-bowl-sponge', 'Brown Bowl Sponge', 'Cribrochalina vasculum', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brown-octopus-sponge', 'Brown Octopus Sponge', 'Ectyoplasia ferox', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brown-variable-sponge', 'Brown Variable Sponge', 'Halisarca caerulea', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('buried-sponge', 'Buried Sponge', 'Dictyonella funicularis', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('pale-calcareous-sponge', 'Pale Calcareous Sponge', 'Leucaltis clathria', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('chicken-liver-sponge', 'Chicken Liver Sponge', 'Monanchora arbuscula', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('serrated-strap-alga', 'Serrated Strap Alga', 'Phormidium ciliolata', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('citron-sponge', 'Citron Sponge', 'Geodia gibberosa', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('convoluted-orange-sponge', 'Convoluted Orange Sponge', 'Leucandra barbata', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('fuzzy-thicket-alga', 'Fuzzy Thicket Alga', 'Dichotomaria obtusata', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blue-encrusting-sponge', 'Blue Encrusting Sponge', 'Dysidea etheria', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('elephant-ear', 'Elephant Ear', 'Desmapsamma anchorata', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brazilian-twig-alga', 'Brazilian Twig Alga', 'Amphiroa brasiliana', 'marine_plant', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('high-veined', 'High-Veined', 'Chondrilla hartmani', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('goblet-sponge', 'Goblet Sponge', 'Ircinia campana', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-ball-sponge', 'Black Ball Sponge', 'Ircinia felix', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('green-finger-sponge', 'Green Finger Sponge', 'Dragmacidon lunaecharta', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('orange-branching-sponge', 'Orange Branching Sponge', 'Ptilocaulis marquezii', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('horned', 'Horned', 'Agelas cervicornis', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('corky-sea-fingers', 'Corky Sea Fingers', 'Briareum asbestinum', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('baroque-cave-cup-coral', 'Baroque Cave Cup Coral', 'Coenocyathus caribbeana', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('branching-tube-sponge', 'Branching Tube Sponge', 'Tube Sponges', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('speckled', 'Speckled', 'Rhizosmilia maculata', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('flattened', 'Flattened', 'Hyattella cavernosa', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('diffuse-ivory-tree-coral', 'Diffuse Ivory Tree Coral', 'Oculina diffusa', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('elkhorn-coral', 'Elkhorn Coral', 'Acropora palmata', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blade-fire-coral', 'Blade Fire Coral', 'Acropora cervicornis', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('azure-vase-sponge', 'Azure Vase Sponge', 'Smenospongia plicifera', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('branching', 'Branching', 'Thalassia janiae', 'sponge', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('elongated-flower-coral', 'Elongated Flower Coral', 'Mussa angulosa', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('golden-sea-spray', 'Golden Sea Spray', 'Muricea muricata', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('golfball-coral', 'Golfball Coral', 'Colpophyllia natans', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('honeycomb-plate-coral', 'Honeycomb Plate Coral', 'Agaricia fragilis', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('lettuce-coral', 'Lettuce Coral', 'Agaricia agaricites', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('encrusting', 'Encrusting', 'Muricea humilis', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bushy-black-coral', 'Bushy Black Coral', 'Antipathes caribbeana', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('feather', 'Feather', 'Antipathes atlantica', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('maze-coral', 'Maze Coral', 'Meandrina danae', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blue-crust-coral', 'Blue Crust Coral', 'Diploria branneri', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('pillar-coral', 'Pillar Coral', 'Dendrogyra cylindrus', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('common-sea-fan', 'Common Sea Fan', 'Gorgonia flabellum', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('lowridge', 'Lowridge', 'Mycetophyllia danaana', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('banded-tube-dwelling-anemone', 'Banded Tube-Dwelling Anemone', 'Isarachnanthus nocturnus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('sea-plumes', 'Sea Plumes', 'Mycetophyllia bipinnata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('beaded', 'Beaded', 'Actinoporus elegans', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blistered-grass', 'Blistered Grass', 'Bunodeopsis antilliensis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('rough-sea', 'Rough Sea', 'Muricea elongata', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('corkscrew', 'Corkscrew', 'Bunodosoma granuliferum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black', 'Black', 'Plexaura homomalla', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('giant', 'Giant', 'Condylactis gigantea', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('delicate-spiny', 'Delicate Spiny', 'Muricea laxa', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('doughnut', 'Doughnut', 'Eunicea spp.', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bushy', 'Bushy', 'Ellisella elongata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-coral-barnacle', 'Black Coral Barnacle', 'Lepas anserifera', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('giant-basket-star', 'Giant Basket Star', 'Astrophyton muricatum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('sea-rod', 'Sea Rod', 'Analcidometra armata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('angular-brittle-star', 'Angular Brittle Star', 'Lysmata cinerea', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bandedarm', 'Bandedarm', 'Ophioderma appressa', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blunt-spined', 'Blunt-Spined', 'Ophiocoma echinata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('boulder', 'Boulder', 'Orbicella annularis', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('elliptical', 'Elliptical', 'Dichocoenia stokesi', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('great', 'Great', 'Montastraea cavernosa', 'coral', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bleeding-teeth-bryozoan', 'Bleeding Teeth Bryozoan', 'Canda simplex', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('purple-reef-fan', 'Purple Reef Fan', 'Bugula minima', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('green-clinging-crab', 'Green Clinging Crab', 'Damithrax hispidus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('burrowing-shrimp-lobster', 'Burrowing/Shrimp Lobster', 'Caprella spp.', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('buttercup-lucine', 'Buttercup Lucine', 'Anodontia alba', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('hairy-coral', 'Hairy Coral', 'Batodaeus urinator', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('caribbean-red-chiton', 'Caribbean Red Chiton', 'Acanthochitona hemphilli', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('hairy-sponge', 'Hairy Sponge', 'Dromia erythropus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('heart-urchin-pea', 'Heart Urchin Pea', 'Carpilius corallinus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('hoary-rubble', 'Hoary Rubble', 'Calappa flammea', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('beroe-comb-jelly', 'Beroe Comb Jelly', 'Beroe forskalii', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bolinopsis', 'Bolinopsis', 'Bolinopsis vitrea', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('nopides-decorator', 'Nopides Decorator', 'Chorinus heros', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('shortfinger-neck', 'Shortfinger Neck', 'Coryrhynchus sidneyi', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('hawkwing-conch', 'Hawkwing Conch', 'Ocyropsis gallus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('milk', 'Milk', 'Lithopoma costatus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('agate-cone-snail', 'Agate Cone Snail', 'Cittarium pica', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('spotted-porcelain', 'Spotted Porcelain', 'Porcellana sayana', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cardinal', 'Cardinal', 'Conus cardinalis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('yellowline-arrow', 'Yellowline Arrow', 'Stenorhynchus seticornis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('florida-corallimorph', 'Florida Corallimorph', 'Corynactis caribbeorum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('warty', 'Warty', 'Rhodactis osculifera', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('chocolate-cyphoma', 'Chocolate Cyphoma', 'Eunice acicularis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('atlantic-deer-cowrie', 'Atlantic Deer Cowrie', 'Erosaria acicularis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('flamingo-tongue', 'Flamingo Tongue', 'Cyphoma gibbosum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-spotted-feather-duster', 'Black-Spotted Feather Duster', 'Branchiomma nigromaculatum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('ghost', 'Ghost', 'Bispira melanostigma', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('social', 'Social', 'Bispira brunnea', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('channel-clinging', 'Channel Clinging', 'Maguimithrax spinosissimus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('antillean-fileclam', 'Antillean Fileclam', 'Ctenoides mitis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bicolored-flatworm', 'Bicolored Flatworm', 'Penaeus bicolor marcusorum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-velvet', 'Black Velvet', 'Maritigrella crozieri', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('harris', 'Harris’', 'Hypsicomus newmanae', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cunina-jelly-jellyfish', 'Cunina Jelly/Jellyfish', 'Botryllus forskalea', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('delicate-hydromedusa', 'Delicate Hydromedusa', 'Cassiopea frondosa', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('moon', 'Moon', 'Alatina alata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('headshield-slugs', 'Headshield Slugs', 'Chelidonura berolina', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-aglaja', 'Black Aglaja', 'Atrina cubana', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('caribbean-spiny-lobster', 'Caribbean Spiny Lobster', 'Enoplometopus antillensis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('red-banded', 'Red Banded', 'Justitia longimana', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('emperor-helmet', 'Emperor Helmet', 'Cassis flammea', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('ciliated-false-squilla-mantis', 'Ciliated False Squilla Mantis', 'Leucozonia oerstedii', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blue-eye-hermit', 'Blue-Eye Hermit', 'Clibanarius tricolor', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('dark', 'Dark', 'Neogonodactylus curacaoensis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('giant-2', 'Giant', 'Dardanus venosus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('orangeclaw', 'Orangeclaw', 'Calcinus tibicen', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('glowing-marginella', 'Glowing Marginella', 'Eratoidea sulcata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('barbados-miter', 'Barbados Miter', 'Cerithium litteratum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('algae-hydroid', 'Algae Hydroid', 'Gymnangium allmani', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brown-mussel', 'Brown Mussel', 'Crassostrea rhizophorae', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('mysids', 'Mysids', 'Anoplodactylus spp.', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('feather-bush', 'Feather Bush', 'Dentitheca dendritica', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('antillean-doris-nudibranch', 'Antillean Doris Nudibranch', 'Aphelodoris antillensis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-spotted', 'Black-Spotted', 'Ceratophyllidia papilligera', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cassiopea-dondice', 'Cassiopea Dondice', 'Dondice occidentalis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('agua-viva-jelly-jellyfish', 'Agua Viva Jelly/Jellyfish', 'Olindias sambaquiensis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('crisscross-tritonia', 'Crisscross Tritonia', 'Bornella calcarata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('gold-crowned-sea-goddess', 'Gold-Crowned Sea Goddess', 'Doriprismatica sedna', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('velvet-elysia-sapsucking-slugs', 'Velvet Elysia Sapsucking Slugs', 'Conus flava', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('longhorn', 'Longhorn', 'Austraeolis catina', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('knobby-scallop', 'Knobby Scallop', 'Caribachlamys ornata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('sea-angel', 'Sea Angel', 'Corolla spectabilis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('beaded-sea-cucumber', 'Beaded Sea Cucumber', 'Actinopyga agassizii', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('florida', 'Florida', 'Astichopus multifidus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('princeps', 'Princeps', 'Macrotritopus princeps', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('tufted', 'Tufted', 'Tritoniopsis frydis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('white-speckled', 'White-Speckled', 'Pauleo jubatus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blunt-armed-sea-star', 'Blunt-Armed Sea Star', 'Asterinides folium', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('atlantic-longarm-octopus', 'Atlantic Longarm Octopus', 'Callistoctopus macropus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cushion', 'Cushion', 'Astropecten duplicatus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('atlantic-thorny-oyster', 'Atlantic Thorny Oyster', 'Spondylus americanus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('atlantic-black-seahare', 'Atlantic Black Seahare', 'Bursatella leachii', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('baba-s', 'Baba’s', 'Cassiopea juliana', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('sapsucking-slugs', 'Sapsucking Slugs', 'Condylactis crispata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('antilles-oxynoe', 'Antilles Oxynoe', 'Costasiella ocellifera', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('antiguan-cave-shrimp', 'Antiguan Cave Shrimp', 'Janicea antiguensis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('banded-coral', 'Banded Coral', 'Ancylomenes pedersoni', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-coral', 'Black Coral', 'Latreutes fucorum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('horned-elysia', 'Horned Elysia', 'Elysia cornigera', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brown-crinoid', 'Brown Crinoid', 'Pseudopontonides crinoidalis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brown-grass', 'Brown Grass', 'Metapenaeopsis goodei', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('circled-bumblebee', 'Circled Bumblebee', 'Gnathophylloides mineri', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('crimson-coral', 'Crimson Coral', 'Brachycarpus biunguiculatus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('giant-atlantic-pyram-snails', 'Giant Atlantic Pyram Snails', 'Americoliva sayana', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('granular-frog-snail', 'Granular Frog Snail', 'Bursa granularis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('manning-s-grass', 'Manning’s Grass', 'Hippolyte nicholsoni', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('longspine-starsnail', 'Longspine Starsnail', 'Calliostoma javanicum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('red-night', 'Red Night', 'Cinetorhynchus manningi', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('smooth-scotch-bonnet', 'Smooth Scotch Bonnet', 'Semicassis granulata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('tusk-snail', 'Tusk Snail', 'Bulla occidentalis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('west-indian-dovesnail', 'West Indian Dovesnail', 'Columbella mercatoria', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('spotted-cleaner', 'Spotted Cleaner', 'Pyrosoma yucatanicus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('banded-snapping-shrimp', 'Banded Snapping Shrimp', 'Alpheus spp.', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('clubclaw', 'Clubclaw', 'Bunodosoma armatus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('apricot-sidegill-slug', 'Apricot Sidegill Slug', 'Berthellina engeli', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('atlantic-brief-squid', 'Atlantic Brief Squid', 'Abralia veranyi', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('barbed-wire-siphonophore', 'Barbed Wire Siphonophore', 'Agalma elegans', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('swimming-crabs', 'Swimming Crabs', 'Achelous ordwayi', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('spiral', 'Spiral', 'Forskalia tholoides', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('azure-overgrowing-tunicate', 'Azure Overgrowing Tunicate', 'Diplosoma glandulosum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-condominium', 'Black Condominium', 'Eudistoma obscuratum', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-overgrowing', 'Black Overgrowing', 'Botrylloides spp.', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-2', 'Black', 'Clavelina spp.', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bluebell', 'Bluebell', 'Ascidia sydneiensis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('peanut-worms-worms', 'Peanut Worms Worms', 'Arenicola cristata', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('polycheate-worms', 'Polycheate Worms', 'Chloeia viridis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('geometric-encrusting', 'Geometric Encrusting', 'Botryllus spp.', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('ribbon-worms', 'Ribbon Worms', 'Baseodiscus spp.', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('robust-syllid-worm', 'Robust Syllid Worm', 'Haplosyllis spongicola', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brown-sponge-zoanthid', 'Brown Sponge Zoanthid', 'Bergia catenularis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('brown', 'Brown', 'Pomatostegus grandis', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('knobbly', 'Knobbly', 'Metapenaeopsis tuberculatus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('mat', 'Mat', 'Zoanthus pulchellus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('inflated-sea-biscuit-urchin', 'Inflated Sea Biscuit Urchin', 'Clypeaster rosaceus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('jewel', 'Jewel', 'Clypeaster subdepressus', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('long-spined', 'Long-Spined', 'Astropyga magnifica', 'invertebrate', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cherubfish-angelfish', 'Cherubfish Angelfish', 'Centropyge argi', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('queen-angelfish', 'Queen Angelfish', 'Holacanthus ciliaris', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('balao', 'Balao', 'Hemiramphus balao', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('balloonfish', 'Balloonfish', 'Diodon holocanthus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('great-barracuda', 'Great Barracuda', 'Sphyraena barracuda', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('guaguanche', 'Guaguanche', 'Cheilopogon melanurus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bantam-bass', 'Bantam Bass', 'Liopropoma carmabi', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('chalk', 'Chalk', 'Serranus annularis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('tobaccofish', 'Tobaccofish', 'Paraclinus tabacarius', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blackcap-basslet', 'Blackcap Basslet', 'Gramma linki', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('banded-butterflyfish', 'Banded Butterflyfish', 'Enchelycore striatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('foureye', 'Foureye', 'Chaetodon aculeatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('barred-cardinalfish', 'Barred Cardinalfish', 'Tozeuma binotatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('polkadot-batfish', 'Polkadot Batfish', 'Astroscopus y-graecum', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blackfin', 'Blackfin', 'Astrapogon puncticulatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bridle', 'Bridle', 'Apogon aurolineatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bigeye', 'Bigeye', 'Heteropriacanthus cruentatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('broadsaddle', 'Broadsaddle', 'Trapania maculatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('arrow-blenny', 'Arrow Blenny', 'Chaenopsis limbaughi', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bald', 'Bald', 'Paraclinus barbatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blackbelly', 'Blackbelly', 'Ophioblennius macclurei', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blackcheek', 'Blackcheek', 'Starksia nanodes', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('caribbean', 'Caribbean', 'Spondylus maria', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('diamond', 'Diamond', 'Malacoctenus aurolineatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('downy', 'Downy', 'Labrisomus cricota', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('filament', 'Filament', 'Emblemaria hyltoni', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('flagfin-glass', 'Flagfin Glass', 'Emblemariopsis bottomei', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blue-chromis', 'Blue Chromis', 'Chromis cyanea', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('palehead', 'Palehead', 'Enneanectes altivelis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bermuda-chub', 'Bermuda Chub', 'Centropomus undecimalis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('ribbon', 'Ribbon', 'Cerdale pandionis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('red-clingfish', 'Red Clingfish', 'Acyrtus rubiginosus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('coney', 'Coney', 'Emblemaria fulva', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('roughhead', 'Roughhead', 'Acanthemblemaria aspera', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bandtooth-conger', 'Bandtooth Conger', 'Ariosoma balearicum', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bluespotted-cornetfish', 'Bluespotted Cornetfish', 'Fistularia tabacaria', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('honeycomb-cowfish', 'Honeycomb Cowfish', 'Acanthostracion polygonius', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('scrawled', 'Scrawled', 'Stenopus quadricornis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('reef-croaker', 'Reef Croaker', 'Albula vulpes', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('beaugregory-damselfish', 'Beaugregory Damselfish', 'Abudefduf taurus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bicolor', 'Bicolor', 'Stegastes adustus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cocoa', 'Cocoa', 'Rhizoprionodon variabilis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blue-runner', 'Blue Runner', 'Decapterus macarellus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('key-brotula', 'Key Brotula', 'Cerdale floridana', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('sergeant-major', 'Sergeant Major', 'Abudefduf saxatilis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bridled-burrfish', 'Bridled Burrfish', 'Chilomycterus antennatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('yellowtail', 'Yellowtail', 'Microspathodon chrysurus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('leopard-goby', 'Leopard Goby', 'Bathygobius soporator', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('linesnout', 'Linesnout', 'Carcharhinus lori', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('masked', 'Masked', 'Coryphopterus dicrus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blackspotted-eel', 'Blackspotted Eel', 'Ahlia egmontis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('orangesided', 'Orangesided', 'Gobiosoma dilepis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('orangespotted', 'Orangespotted', 'Nes longus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('cusk', 'Cusk', 'Echiophis punctifer', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('patch-reef', 'Patch-Reef', 'Bascanichthys glaucofraenum', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('rusty', 'Rusty', 'Lyhrypnus heterochroma', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('sharknose', 'Sharknose', 'Elacatinus colini', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('fringed-filefish', 'Fringed Filefish', 'Aluterus monoceros', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('scrawled-2', 'Scrawled', 'Thersandrus scriptus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('graysby', 'Graysby', 'Cephalopholis cruentata', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-grouper', 'Black Grouper', 'Epinephelus morio', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('goliath-grouper', 'Goliath Grouper', 'Epinephelus itajara', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('channel-flounder', 'Channel Flounder', 'Achirus lineatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('tiger', 'Tiger', 'Hypoplectrus tigris', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bluestriped-grunt', 'Bluestriped Grunt', 'Emmelichthyops atlanticus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('peacock', 'Peacock', 'Bothus lunatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('caesar', 'Caesar', 'Haemulon carbonarium', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('flying-gunard', 'Flying Gunard', 'Dactylopterus volitans', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('dwarf-frogfish', 'Dwarf Frogfish', 'Antennarius multiocellatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('porkfish', 'Porkfish', 'Anisotremus surinamensis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('smallmouth', 'Smallmouth', 'Liopropoma chrysargyreum', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('spotted-goatfish', 'Spotted Goatfish', 'Amblycirrhitus pinos', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('barred-hamlet', 'Barred Hamlet', 'Fowlerichthys puella', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('masked-2', 'Masked', 'Hypoplectrus providencianus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('highhat', 'Highhat', 'Equetus lanceolatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('redband-parrotfish', 'Redband Parrotfish', 'Scarus coeruleus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('redtail', 'Redtail', 'Ocyurus vetula', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('hogfish', 'Hogfish', 'Lachnolaimus maximus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('stoplight', 'Stoplight', 'Phaeoptyx viride', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('spanish', 'Spanish', 'Bodianus pulchellus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('striped', 'Striped', 'Neoniphon iseri', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('yellowtail-2', 'Yellowtail', 'Cryptotomus roseus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('almaco-jack', 'Almaco Jack', 'Carangoides bartholomaei', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('banded-pipefish', 'Banded Pipefish', 'Hippocampus erectus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('caribbean-2', 'Caribbean', 'Cosmocampus albirostris', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('crevalle', 'Crevalle', 'Echeneis hippos', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('horse-eye', 'Horse-Eye', 'Alectis ciliaris', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('pipehorse', 'Pipehorse', 'Amphelikturus dendriticus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('dusky-jawfish', 'Dusky Jawfish', 'Malacanthus plumieri', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('yellowhead', 'Yellowhead', 'Opistognathus aurifrons', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('jolthead-porgy', 'Jolthead Porgy', 'Calamus bajonado', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('lionfish-invasive', 'Red Lionfish', 'Pterois volitans', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('sand-diver', 'Sand Diver', 'Synodus intermedius', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('caribbean-torpedo-ray', 'Caribbean Torpedo Ray', 'Bathytoshia centroura', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('chain-moray', 'Chain Moray', 'Echidna catenata', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('spotted-eagle-ray', 'Spotted Eagle Ray', 'Aetobatus narinari', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('razorfish-green', 'Razorfish Green', 'Xyrichtys splendens', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('green-moray', 'Green Moray', 'Gymnothorax funebris', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('pearly', 'Pearly', 'Xyrichtys martinicensis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('common-remora', 'Common Remora', 'Echeneis naucrates', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('viper', 'Viper', 'Enchelycore nigricans', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('coral-scorpionfish', 'Coral Scorpionfish', 'Scorpaena albifimbria', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('plumed', 'Plumed', 'Ogilbia grandicornis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('midnight', 'Midnight', 'Scarus guacamaia', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('longsnout', 'Longsnout', 'Megalops reidi', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('whitespotted-toadfish', 'Whitespotted Toadfish', 'Sanopus astrifer', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('atlantic-sharpnose-shark', 'Atlantic Sharpnose Shark', 'Carcharhinus leucas', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blacktip', 'Blacktip', 'Carcharhinus falciformis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-durgon-triggerfish', 'Black Durgon Triggerfish', 'Balistes capriscus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('queen', 'Queen', 'Vexillum vetula', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('caribbean-reef-shark', 'Caribbean Reef Shark', 'Carcharhinus perezii', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('atlantic-tripletail', 'Atlantic Tripletail', 'Chaetodipterus faber', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('whale', 'Whale', 'Rhincodon typus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('trumpetfish', 'Trumpetfish', 'Aulostomus maculatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('smooth', 'Smooth', 'Haemulon triqueter', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('spotted', 'Spotted', 'Lactophrys bicaudalis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('black-snapper', 'Black Snapper', 'Apsilus dentatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blackfin-2', 'Blackfin', 'Lutjanus buccanella', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blackear-wrasse', 'Blackear Wrasse', 'Clepticus parrae', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bluehead', 'Bluehead', 'Thalassoma bifasciatum', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('dog', 'Dog', 'Lutjanus analis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('clown', 'Clown', 'Halichoeres maculipinna', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('puddingwife', 'Puddingwife', 'Lyhrypnus radiatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('slippery-dick', 'Slippery Dick', 'Halichoeres bivittatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('schoolmaster', 'Schoolmaster', 'Lutjanus apodus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('yellowhead-2', 'Yellowhead', 'Halichoeres garnoti', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('spotted-drum', 'Spotted Drum', 'Coryphaena punctatus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('squirrelfish', 'Squirrelfish', 'Holocentrus adscensionis', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('blue-tang-surgeonfish', 'Blue Tang Surgeonfish', 'Stenorhynchus coeruleus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('doctorfish', 'Doctorfish', 'Acanthurus chirurgus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('parrotfishes', 'Parrotfishes', 'Haemulon album', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('green-sea-turtle', 'Green Sea Turtle', 'Chelonia mydas', 'sea_turtle', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('hawksbill-sea-turtle', 'Hawksbill Sea Turtle', 'Eretmochelys imbricata', 'sea_turtle', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('loggerhead-sea-turtle', 'Loggerhead Sea Turtle', 'Caretta caretta', 'sea_turtle', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('leatherback-sea-turtle', 'Leatherback Sea Turtle', 'Dermochelys coriacea', 'sea_turtle', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('bottlenose-dolphin', 'Bottlenose Dolphin', 'Tursiops truncatus', 'marine_mammal', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('atlantic-spotted-dolphin', 'Atlantic Spotted Dolphin', 'Stenella frontalis', 'marine_mammal', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('west-indian-manatee', 'West Indian Manatee', 'Trichechus manatus', 'marine_mammal', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('nurse-shark', 'Nurse Shark', 'Ginglymostoma cirratum', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('southern-stingray', 'Southern Stingray', 'Hypanus americanus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('splendid-toadfish', 'Splendid Toadfish', 'Sanopus splendidus', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('french-angelfish', 'French Angelfish', 'Pomacanthus paru', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('stoplight-parrotfish', 'Stoplight Parrotfish', 'Sparisoma viride', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true),
('spotted-moray', 'Spotted Moray', 'Gymnothorax moringa', 'fish', 'Caribbean Reef Life (Mickey Charteris, 3rd ed) — names only', true)
on conflict (scientific_name) do update set
  common_name = excluded.common_name,
  category = excluded.category,
  source_reference = excluded.source_reference,
  is_verified = true;
